### ISSUE TITLE
不蒜子域名更改

### ISSUE THREAD

**Issue by PRIEWIENV** [SukkaW/hexo-theme-suka#40]
**I certify that I have first consulted** (check with "x")

**我确认我已经查看了** (选择时请使用 "x" 取代方括号中的空格)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Suka Theme documentation | Suka Theme 文档](https://theme.suka.moe/docs/)
- [x] [Suka theme issues | Suka 主题的其它 issue](https://github.com/SukkaW/hexo-theme-suka/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

## 我正在申请  (选择时请使用 "x" 取代方括号中的空格)

- [x] bug report | 反馈一个 Bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

----

### 我使用的平台

Windows Sub Linux

### 我使用的浏览器
Version 69.0.3497.100 (Official Build) (64-bit)

### 开发者面板的控制台日志

```
Failed to load resource: the server responded with a status of 404 () dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js:1 
```

### 预期结果和你的实际结果

本应有不蒜子的计数，但是没有显示。

### 推测原因

[不蒜子主页](https://busuanzi.ibruce.info/)显示：
> 因七牛强制过期『dn-lbstatics.qbox.me』域名，与客服沟通无果，只能更换域名到『busuanzi.ibruce.info』！

所以推测是静态文件地址改了。

**Comment by SukkaW** [comment]
收到，我会切换到带 不蒜子 JS Mirror 的地址

```
https://cdn.jsdelivr.net/npm/busuanzi@2.3.0/bsz.pure.mini.js
```

你也可以暂时在 主题配置文件中 `vendor.busuanzi` 设置为上述地址来暂时恢复对不蒜子的使用。
