### ISSUE TITLE
能否设置在正文中不显示章节目录，但是保留文章右侧的章节目录？

### ISSUE THREAD

**Issue by sunhb** [SukkaW/hexo-theme-suka#77]
### 介绍你需要的特性
启用文章章节目录后，会在文章的正文中和文章的右侧显示章节目录。但是我的需求是只在右侧显示章节目录，同时文章正文中不显示。也许已经有这个功能了，但是我实在是没有找到相关配置。

**Comment by SukkaW** [comment]
为什么你的正文中会有目录？

**Comment by sunhb** [comment]
<img width="1503" alt="屏幕快照 2019-04-01 17 26 43" src="https://user-images.githubusercontent.com/6211116/55317845-ecc13c00-54a3-11e9-9bc3-eeab445cd018.png">


您可以通过[这里](https://oncno.com/2018/09/01/markdown-page-test/)查看这个页面的内容

**Comment by sunhb** [comment]
不知道我的问题有没有描述清楚

**Comment by sunhb** [comment]
Sorry 我的描述确实有问题，我描述的不对。

**Comment by sunhb** [comment]
这貌似是个bug，实际上是他把整个 `toc`分成了两个部分，一部分在右侧，第二部分跑到了文章顶部。

**Comment by sunhb** [comment]
### 问题描述

**Comment by sunhb** [comment]
### 问题描述：
开启`toc`后，文章的目录信息排版不正确
### 现象：
章节信息被分割成两部分，第一部分显示的位置正确，第二部分显示在了文章内容里。并跟随文章滚动。如图：
![image](https://user-images.githubusercontent.com/6211116/55320965-0e71f180-54ab-11e9-8b97-b5ba12db86ab.png)

您可以通过[这个页面](https://oncno.com/2018/09/01/markdown-page-test/)查看这个页面的内容

### 符合预期的结果：
文章章节目录(`toc`)不会被分割，并正确显示在文章右侧位置。

感谢🙏

**Comment by D0ot** [comment]
同样碰到了这个问题，使用多级目录就会出现。
